### PR TITLE
Compare normalized requests

### PR DESCRIPTION
**Pull request by jplindstrom**
This implements #6

### CODE REVIEW

**Comment by jplindstrom** [comment]
Hey, any progress on getting this onto CPAN?

**Comment by PopeFelix** [comment]
I'm sorry, I completely spaced on this. I'll work on getting it in this
week.

On Mon, Jun 20, 2016 at 9:58 AM, Johan Lindstrom notifications@github.com
wrote:

> Hey, any progress on getting this onto CPAN?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PopeFelix/Mojo-UserAgent-Mockable/pull/7#issuecomment-227202865,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAJqGNnLanPhOlbZBSC3CNq332cOYKqCks5qNsa2gaJpZM4I0Nyx
> .

## 

Kit Peters, W0KEH
GPG public key fingerpint: 1A12 04B6 0C80 306A B292  14FD 2C7A 1037 F666
46A7
Hello to any and all NSA, DEA, or other government or non-government agents
reading this email.  Tell me about your life; I'll tell you about mine.

**Comment by PopeFelix** [comment]
It looks good, but I would like to see a test that shows it working in playback. End to end testing is important.

**Comment by jplindstrom** [comment]
I completely missed your reply, so I didn't get around to writing this test until now.

Please let me know if you need anything else.

**Pull request merged**
